// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce5Fab.DataAcsess;

#nullable disable

namespace eCommerce5Fab.DataAcsess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240206071629_AddCulemIsActiveBaseModel")]
    partial class AddCulemIsActiveBaseModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClassLibrary1eCommerce5Fab.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "Phone",
                            IsActive = true,
                            Name = "Phone"
                        },
                        new
                        {
                            Id = "Laptop",
                            IsActive = true,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = "Cumputer",
                            IsActive = true,
                            Name = "Cumputer"
                        },
                        new
                        {
                            Id = "Watch",
                            IsActive = true,
                            Name = "Watch"
                        },
                        new
                        {
                            Id = "Matchine",
                            IsActive = true,
                            Name = "Matchine"
                        });
                });

            modelBuilder.Entity("ClassLibrary1eCommerce5Fab.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ClassLibrary1eCommerce5Fab.Models.Product", b =>
                {
                    b.HasOne("ClassLibrary1eCommerce5Fab.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
